### ISSUE TITLE
Durations can't be formatted with library

### ISSUE THREAD

**Issue by buckett** [heruan/humanize#4]
If you attempt to format an Instant with:

    String duration = HumanizeTime.fromNow(Instant.now());

you get an error:

```
java.time.temporal.UnsupportedTemporalTypeException: Unsupported unit: Years
	at java.base/java.time.Instant.until(Instant.java:1156) ~[na:na]
	at java.base/java.time.temporal.ChronoUnit.between(ChronoUnit.java:272) ~[na:na]
	at to.lova.humanize.time.HumanizeTime.from(HumanizeTime.java:130) ~[humanize-time-0.1.2.jar:na]
	at to.lova.humanize.time.HumanizeTime.fromNow(HumanizeTime.java:119) ~[humanize-time-0.1.2.jar:na]
	at to.lova.humanize.time.HumanizeTime.fromNow(HumanizeTime.java:63) ~[humanize-time-0.1.2.jar:na]
	at to.lova.humanize.time.HumanizeTime.fromNow(HumanizeTime.java:41) ~[humanize-time-0.1.2.jar:na]
```

**Comment by heruan** [comment]
Thank you for reporting this. It is a known issue with `Instant`, see for example: https://stackoverflow.com/questions/39907925/why-instant-does-not-support-operations-with-chronounit-years

Did you try using a `ZonedDateTime`?
